---

version: '3.8'

services:
  app:
    image: node:14-slim
    working_dir: /var/local/app/
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ${PWD}/
        target: /var/local/app/
      - type: volume
        source: node_modules
        target: /var/local/app/node_modules

volumes:
  node_modules:
